## 'Assumed that the file is downloaded.
t <- read.table("household_power_consumption.txt", header = TRUE, sep = ";",stringsAsFactors=F)
t <- t[which(t$Date == '1/2/2007' | t$Date == '2/2/2007'),] 
t$dT <- strptime(paste(t$Date, t$Time, sep = " : "), format = "%e/%m/%Y : %H:%M:%S") 
t$Global_active_power <- as.numeric(t$Global_active_power) 
t$Global_reactive_power <- as.numeric(t$Global_reactive_power) 
t$Global_intensity <- as.numeric(t$Global_intensity) 
t$Sub_metering_1 <- as.numeric(t$Sub_metering_1)
t$Sub_metering_2 <- as.numeric(t$Sub_metering_2) 
t$Sub_metering_3 <- as.numeric(t$Sub_metering_3) 
png("plot3.png")
plot(t$dT,t$Sub_metering_1,type='n',main = "", xlab="", ylab="Energy sub metering") 
lines(t$dT,t$Sub_metering_1, type='l', col = "black") 
lines(t$dT,t$Sub_metering_2, type='l', col = "red") 
lines(t$dT,t$Sub_metering_3, type='l', col = "blue")
legdt <- max(t$dT)-.35*(max(t$dT)-min(t$dT))
legmt <- max(t$Sub_metering_1)-.1*(max(t$Sub_metering_1)-min(t$Sub_metering_1))
legend(legdt,legmt, c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1), lwd=c(1.4,1.4,1.4),col=c("black","red","blue")) 
dev.off()
